<?php
/**
 * aurora.php - Northern Lights image gallery
 *
 * Shows webcam images identified as likely containing aurora borealis,
 * organised by month with the same navigation style as webcam.php.
 *
 * Reads aurora.json generated by aurora_scan.py:
 *   python aurora_scan.py /path/to/images --threshold 0.3 --night \
 *     --json-output /path/to/webcam/aurora.json
 */

require_once 'WebcamConfig.php';
require_once 'NavigationHelper.php';

error_reporting(E_ERROR | E_PARSE);
setlocale(LC_ALL, WebcamConfig::LOCALE);
date_default_timezone_set(WebcamConfig::TIMEZONE);

// ============================================================
// Load aurora data
// ============================================================

$all_images = [];
foreach (glob(__DIR__ . '/aurora-*.json') as $json_file) {
    $decoded = json_decode(file_get_contents($json_file), true);
    if (is_array($decoded)) {
        $all_images = array_merge($all_images, $decoded);
    }
}

// Build sorted list of YYYYMM strings that have aurora images.
$months_with_images = [];
foreach ($all_images as $img) {
    $ym = substr($img['timestamp'], 0, 6);
    $months_with_images[$ym] = true;
}
ksort($months_with_images);
$months_list = array_keys($months_with_images); // ascending

// ============================================================
// Determine which month to show
// ============================================================

$year  = isset($_GET['year'])  ? (int)$_GET['year']  : 0;
$month = isset($_GET['month']) ? (int)$_GET['month'] : 0;

if (!$year || !$month) {
    if (!empty($months_list)) {
        $latest = end($months_list);
        $year  = (int)substr($latest, 0, 4);
        $month = (int)substr($latest, 4, 2);
    } else {
        $year  = (int)date('Y');
        $month = (int)date('m');
    }
}

$month_str  = sprintf('%02d', $month);
$year_str   = sprintf('%04d', $year);
$current_ym = $year_str . $month_str;

// ============================================================
// Find prev / next months that actually have aurora images
// ============================================================

$prev_url   = false;
$next_url   = false;
$prev_label = false;
$next_label = false;

foreach ($months_list as $ym) {
    if ($ym < $current_ym) {
        $y = (int)substr($ym, 0, 4);
        $m = (int)substr($ym, 4, 2);
        $prev_url   = "?year=$y&month=" . sprintf('%02d', $m);
        $prev_label = date('F Y', mktime(12, 0, 0, $m, 15, $y));
    }
    if ($ym > $current_ym && !$next_url) {
        $y = (int)substr($ym, 0, 4);
        $m = (int)substr($ym, 4, 2);
        $next_url   = "?year=$y&month=" . sprintf('%02d', $m);
        $next_label = date('F Y', mktime(12, 0, 0, $m, 15, $y));
    }
}

// ============================================================
// Filter images for current month, sorted chronologically
// ============================================================

$month_images = array_values(array_filter($all_images, function ($img) use ($current_ym) {
    return substr($img['timestamp'], 0, 6) === $current_ym;
}));
usort($month_images, fn($a, $b) => strcmp($a['timestamp'], $b['timestamp']));

// ============================================================
// Page title
// ============================================================

$title_ts = mktime(12, 0, 0, $month, 15, $year);
$title    = 'Lillevik Lofoten webcam: Northern lights ' . date('F Y', $title_ts);

// ============================================================
// HTML header
// ============================================================

$ga_id      = WebcamConfig::GOOGLE_ANALYTICS_ID;
$clarity_id = WebcamConfig::MICROSOFT_CLARITY_ID;

if (empty($_SERVER['SERVER_NAME'])) {
    $_SERVER['SERVER_NAME'] = 'lilleviklofoten.no';
    $_SERVER['SCRIPT_NAME'] = '/webcam/aurora.php';
}
$script_url = '//' . $_SERVER['SERVER_NAME'] . $_SERVER['SCRIPT_NAME'];

echo '<!DOCTYPE html>' . "\n";
echo '<html lang="en-US">' . "\n";
echo '<head>' . "\n";
echo '  <meta charset="utf-8">' . "\n";
echo '  <meta name="description" content="' . htmlspecialchars(WebcamConfig::SITE_DESCRIPTION) . '">' . "\n";
echo '  <meta name="keywords" content="lofoten,webcam,aurora,northern lights,nordlys,polarlys">' . "\n";
echo '  <meta name="viewport" content="width=device-width, initial-scale=1.0">' . "\n";
echo '  <meta name="robot" content="index">' . "\n";
echo '  <link rel="icon" href="/wp-content/uploads/2020/08/cropped-lillevik-drone-001-20200613-0921-21-2-scaled-2-32x32.jpg" sizes="32x32">' . "\n";
echo '  <link rel="stylesheet" type="text/css" href="css.php">' . "\n";
echo '  <link rel="dns-prefetch" href="//www.googletagmanager.com">' . "\n";
echo '  <link rel="dns-prefetch" href="//www.clarity.ms">' . "\n";
echo '  <link rel="dns-prefetch" href="//cdn.jsdelivr.net">' . "\n";
echo '  <link rel="preconnect" href="https://www.googletagmanager.com" crossorigin>' . "\n";
echo '  <link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin>' . "\n";

if ($prev_url) {
    echo "  <link rel=\"prefetch\" title=\"Previous\" href=\"{$script_url}{$prev_url}\">\n";
}
if ($next_url) {
    echo "  <link rel=\"prefetch\" title=\"Next\" href=\"{$script_url}{$next_url}\">\n";
}

echo "  <title>$title</title>\n";

// Arrow-key navigation
if ($prev_url || $next_url) {
    echo "\n  <script>\n";
    if ($prev_url) echo "    function leftArrowPressed()  { window.location.href=\"$prev_url\"; }\n";
    if ($next_url) echo "    function rightArrowPressed() { window.location.href=\"$next_url\"; }\n";
    echo "    document.onkeydown = function(evt) {\n";
    echo "      evt = evt || window.event;\n";
    echo "      switch (evt.keyCode) {\n";
    if ($prev_url) echo "        case 37: leftArrowPressed();  break;\n";
    if ($next_url) echo "        case 39: rightArrowPressed(); break;\n";
    echo "      }\n";
    echo "    };\n";
    echo "  </script>\n\n";
}

// Google Analytics
echo "  <!-- Google tag (gtag.js) -->\n";
echo "  <script async src=\"https://www.googletagmanager.com/gtag/js?id={$ga_id}\"></script>\n";
echo "  <script>\n";
echo "    window.dataLayer = window.dataLayer || [];\n";
echo "    function gtag(){dataLayer.push(arguments);}\n";
echo "    gtag('js', new Date());\n";
echo "    gtag('config', '{$ga_id}');\n";
echo "  </script>\n\n";

// Microsoft Clarity
echo "  <!-- Microsoft Clarity -->\n";
echo "  <script>\n";
echo "  (function(c,l,a,r,i,t,y){\n";
echo "      c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};\n";
echo "      t=l.createElement(r);t.async=1;t.src=\"https://www.clarity.ms/tag/\"+i;\n";
echo "      y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);\n";
echo "  })(window, document, \"clarity\", \"script\", \"{$clarity_id}\");\n";
echo "  </script>\n\n";

echo "</head>\n";
echo "<body>\n\n";
echo "<h1>$title</h1>\n\n";
echo "<p>\n";
echo "<a href=\".\">Webcam</a>\n";
echo "at\n";
echo "<a href=\"https://lilleviklofoten.no\">Lillevik Lofoten</a>,\n";
echo "Vik, Gimsøy, Lofoten, Norway.\n";
echo "See also: <a href=\"https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/\">Northern lights at Lillevik Lofoten</a>.\n";
echo "</p>\n\n";

// ============================================================
// Month navigation bar
// ============================================================

echo '<p>';
if ($prev_url && $prev_label) {
    echo "<a href=\"$prev_url\">&larr; $prev_label</a> &nbsp;|&nbsp; ";
}
echo '<strong>' . date('F Y', $title_ts) . '</strong>';
if ($next_url && $next_label) {
    echo " &nbsp;|&nbsp; <a href=\"$next_url\">$next_label &rarr;</a>";
}
echo "</p>\n\n";

// ============================================================
// Image grid
// ============================================================

$mini_w = WebcamConfig::MINI_IMAGE_WIDTH;
$mini_h = WebcamConfig::MINI_IMAGE_HEIGHT;

echo '<div class="grid-container">' . "\n";

$count = 0;
foreach ($month_images as $img) {
    $ts    = $img['timestamp']; // YYYYMMDDHHMMSS
    $score = $img['score'];

    $y  = substr($ts, 0, 4);
    $m  = substr($ts, 4, 2);
    $d  = substr($ts, 6, 2);
    $h  = substr($ts, 8, 2);
    $mi = substr($ts, 10, 2);

    $mini_path = "$y/$m/$d/mini/$ts.jpg";
    $src       = file_exists($mini_path) ? $mini_path : "$y/$m/$d/$ts.jpg";
    $alt       = "Lillevik Lofoten webcam: $y-$m-$d $h:$mi";
    $link      = "webcam.php?type=one&image=$ts";
    $label     = "$d $h:$mi (" . number_format($score, 2) . ")";

    echo "  <div class=\"grid-item\">\n";
    echo "    <a href=\"$link\"><img alt=\"$alt\" src=\"$src\" width=\"$mini_w\" height=\"$mini_h\"></a>\n";
    echo "    <span class=\"time\">$label</span>\n";
    echo "  </div>\n";
    $count++;
}

echo "</div>\n\n";

if ($count === 0) {
    echo '<p>(No northern lights photos to display for ' . date('F Y', $title_ts) . '.)</p>' . "\n\n";
}

// ============================================================
// Footer
// ============================================================

$prev_url_safe = $prev_url ?: '';
$next_url_safe = $next_url ?: '';

echo <<<TOUCH

<!-- Touch gestures -->
<script src="https://cdn.jsdelivr.net/npm/hammerjs@2.0.8"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var body = document.body;
        var hammer = new Hammer(body);
        hammer.on('swiperight', function() { window.location.href = '$prev_url_safe'; });
        hammer.on('swipeleft',  function() { window.location.href = '$next_url_safe'; });
    });
</script>
TOUCH;

echo "\n<p>Swipe left/right or use the arrow keys to navigate: ";
if ($next_url && $next_label) echo "<a href=\"$next_url\">$next_label</a> (&rarr;), ";
if ($prev_url && $prev_label) echo "<a href=\"$prev_url\">$prev_label</a> (&larr;)";
echo ".</p>\n\n";

echo "<p style=\"color: rgb(200, 200, 200);\">Northern lights detection by "
   . "<a style=\"color: rgb(200, 200, 200);\" href=\"https://github.com/cloveras/webcam\">aurora_scan.py</a>. "
   . "Score overlay: day + aurora likelihood score.</p>\n\n";

echo "</body>\n</html>\n";
