<?php
/**
 * aurora.php - Northern Lights image gallery
 *
 * Shows webcam images identified as likely containing aurora borealis,
 * organised by month with the same navigation style as webcam.php.
 *
 * Reads aurora.json generated by aurora_scan.py:
 *   python aurora_scan.py /path/to/images --threshold 0.3 --night \
 *     --json-output /path/to/webcam/aurora.json
 */

require_once 'WebcamConfig.php';
require_once 'NavigationHelper.php';
require_once 'lang.php';

error_reporting(E_ERROR | E_PARSE);
setlocale(LC_ALL, WebcamConfig::LOCALE);
date_default_timezone_set(WebcamConfig::TIMEZONE);

// ============================================================
// Load aurora data
// ============================================================

$all_images = [];
foreach (glob(__DIR__ . '/data/aurora-*.json') as $json_file) {
    $decoded = json_decode(file_get_contents($json_file), true);
    if (is_array($decoded)) {
        $all_images = array_merge($all_images, $decoded);
    }
}

// Build sorted list of YYYYMM strings that have aurora images.
$months_with_images = [];
foreach ($all_images as $img) {
    $ym = substr($img['timestamp'], 0, 6);
    $months_with_images[$ym] = true;
}
ksort($months_with_images);
$months_list = array_keys($months_with_images); // ascending

// ============================================================
// Determine which month to show
// ============================================================

$year  = isset($_GET['year'])  ? (int)$_GET['year']  : 0;
$month = isset($_GET['month']) ? (int)$_GET['month'] : 0;
$using_default = !isset($_GET['year']) && !isset($_GET['month']);
$size  = (isset($_GET['size']) && $_GET['size'] === 'large') ? 'large' : 'mini';

if (!$year || !$month) {
    if (!empty($months_list)) {
        $latest = end($months_list);
        $year  = (int)substr($latest, 0, 4);
        $month = (int)substr($latest, 4, 2);
    } else {
        $year  = (int)date('Y');
        $month = (int)date('m');
    }
}

$month_str  = sprintf('%02d', $month);
$year_str   = sprintf('%04d', $year);
$current_ym = $year_str . $month_str;

// ============================================================
// Find prev / next months that actually have aurora images
// ============================================================

$prev_url   = false;
$next_url   = false;
$prev_label = false;
$next_label = false;

foreach ($months_list as $ym) {
    if ($ym < $current_ym) {
        $y = (int)substr($ym, 0, 4);
        $m = (int)substr($ym, 4, 2);
        $size_param = ($size === 'large') ? '&size=large' : '';
        $prev_url   = "?year=$y&month=" . sprintf('%02d', $m) . $size_param . lang_param();
        $prev_label = t_month_year($m, $y);
    }
    if ($ym > $current_ym && !$next_url) {
        $y = (int)substr($ym, 0, 4);
        $m = (int)substr($ym, 4, 2);
        $size_param = ($size === 'large') ? '&size=large' : '';
        $next_url   = "?year=$y&month=" . sprintf('%02d', $m) . $size_param . lang_param();
        $next_label = t_month_year($m, $y);
    }
}

// ============================================================
// Filter images for current month, sorted chronologically
// ============================================================

$month_images = array_values(array_filter($all_images, function ($img) use ($current_ym) {
    return substr($img['timestamp'], 0, 6) === $current_ym;
}));
usort($month_images, fn($a, $b) => strcmp($a['timestamp'], $b['timestamp']));

// Best image for og:image (highest score this month)
$_best = null;
foreach ($month_images as $_img) {
    if (!$_best || $_img['score'] > $_best['score']) $_best = $_img;
}
$_og_image_aurora = $_best
    ? WebcamConfig::WEBCAM_URL . substr($_best['timestamp'],0,4) . '/' . substr($_best['timestamp'],4,2) . '/' . substr($_best['timestamp'],6,2) . '/' . $_best['timestamp'] . '.jpg'
    : '';

// ============================================================
// Page title
// ============================================================

$title = WebcamConfig::SITE_NAME . ' webcam: ' . t('aurora_page_suffix');
if (!$using_default) {
    $title .= ' ' . t_month_year($month, $year);
}

// ============================================================
// HTML header
// ============================================================

$ga_id      = WebcamConfig::GOOGLE_ANALYTICS_ID;
$clarity_id = WebcamConfig::MICROSOFT_CLARITY_ID;

if (empty($_SERVER['SERVER_NAME'])) {
    $_SERVER['SERVER_NAME'] = WebcamConfig::FALLBACK_SERVER_NAME;
    $_SERVER['SCRIPT_NAME'] = '/webcam/aurora.php';
}
$script_url = '//' . $_SERVER['SERVER_NAME'] . $_SERVER['SCRIPT_NAME'];
$_webcam_url = WebcamConfig::WEBCAM_URL;
$_aurora_canonical = $using_default
    ? "{$_webcam_url}aurora.php"
    : "{$_webcam_url}aurora.php?year={$year_str}&month={$month_str}";

header('Cache-Control: public, max-age=1800');
header('Expires: ' . gmdate('D, d M Y H:i:s', time() + 1800) . ' GMT');

echo '<!DOCTYPE html>' . "\n";
echo '<html lang="' . lang_html_attr() . '">' . "\n";
echo '<head>' . "\n";
echo '  <meta charset="utf-8">' . "\n";
$_aurora_meta_desc = htmlspecialchars(strip_tags(t('aurora_seo_description')), ENT_QUOTES, 'UTF-8');
echo '  <meta name="description" content="' . $_aurora_meta_desc . '">' . "\n";
echo '  <meta name="viewport" content="width=device-width, initial-scale=1.0">' . "\n";
echo '  <meta name="robots" content="index, follow">' . "\n";
echo '  <link rel="canonical" href="' . htmlspecialchars($_aurora_canonical) . '">' . "\n";
echo '  <meta property="og:title" content="' . htmlspecialchars($title) . '">' . "\n";
echo '  <meta property="og:description" content="' . $_aurora_meta_desc . '">' . "\n";
echo '  <meta property="og:type" content="website">' . "\n";
echo '  <meta property="og:url" content="' . htmlspecialchars($_aurora_canonical) . '">' . "\n";
if ($_og_image_aurora) {
    echo '  <meta property="og:image" content="' . htmlspecialchars($_og_image_aurora) . '">' . "\n";
}
echo '  <link rel="icon" href="' . WebcamConfig::FAVICON_32 . '" sizes="32x32">' . "\n";
echo '  <link rel="stylesheet" type="text/css" href="css.php?v=' . filemtime(__DIR__ . '/webcam.css') . '">' . "\n";
echo '  <link rel="dns-prefetch" href="//www.googletagmanager.com">' . "\n";
echo '  <link rel="dns-prefetch" href="//www.clarity.ms">' . "\n";
echo '  <link rel="dns-prefetch" href="//cdn.jsdelivr.net">' . "\n";
echo '  <link rel="preconnect" href="https://www.googletagmanager.com" crossorigin>' . "\n";
echo '  <link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin>' . "\n";

if ($prev_url) {
    echo "  <link rel=\"prefetch\" title=\"Previous\" href=\"{$script_url}{$prev_url}\">\n";
}
if ($next_url) {
    echo "  <link rel=\"prefetch\" title=\"Next\" href=\"{$script_url}{$next_url}\">\n";
}

echo lang_hreflang_links('https://lilleviklofoten.no/webcam/aurora.php');
echo "  <title>$title</title>\n";

// Arrow-key navigation
if ($prev_url || $next_url) {
    echo "\n  <script>\n";
    if ($prev_url) echo "    function leftArrowPressed()  { window.location.href=\"$prev_url\"; }\n";
    if ($next_url) echo "    function rightArrowPressed() { window.location.href=\"$next_url\"; }\n";
    echo "    document.onkeydown = function(evt) {\n";
    echo "      evt = evt || window.event;\n";
    echo "      if (window.getSelection().toString()) return;\n";
    echo "      switch (evt.keyCode) {\n";
    if ($prev_url) echo "        case 37: leftArrowPressed();  break;\n";
    if ($next_url) echo "        case 39: rightArrowPressed(); break;\n";
    echo "      }\n";
    echo "    };\n";
    echo "  </script>\n\n";
}

// Google Analytics
echo "  <!-- Google tag (gtag.js) -->\n";
echo "  <script async src=\"https://www.googletagmanager.com/gtag/js?id={$ga_id}\"></script>\n";
echo "  <script>\n";
echo "    window.dataLayer = window.dataLayer || [];\n";
echo "    function gtag(){dataLayer.push(arguments);}\n";
echo "    gtag('js', new Date());\n";
echo "    gtag('config', '{$ga_id}');\n";
echo "  </script>\n\n";

// Microsoft Clarity
echo "  <!-- Microsoft Clarity -->\n";
echo "  <script>\n";
echo "  (function(c,l,a,r,i,t,y){\n";
echo "      c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};\n";
echo "      t=l.createElement(r);t.async=1;t.src=\"https://www.clarity.ms/tag/\"+i;\n";
echo "      y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);\n";
echo "  })(window, document, \"clarity\", \"script\", \"{$clarity_id}\");\n";
echo "  </script>\n\n";

echo "</head>\n";
echo "<body>\n\n";
echo "<h1>$title</h1>\n\n";
echo "<p>" . t('aurora_intro') . " " . t('aurora_see_also') . "</p>\n\n";

// ============================================================
// Month navigation bar
// ============================================================

$base_url = "?year=$year_str&month=$month_str" . lang_param();
$nav_links = [];
if ($prev_url && $prev_label) {
    $nav_links[] = "<a href=\"$prev_url\">&larr; $prev_label</a>";
}
if ($next_url && $next_label) {
    $nav_links[] = "<a href=\"$next_url\">$next_label &rarr;</a>";
}
$nav_links[] = "<a href=\"." . lang_query() . "\">" . t('nav_webcam') . "</a>";
if ($size === 'large') {
    $nav_links[] = "<a href=\"{$base_url}\">" . t('nav_mini_photos') . "</a>";
} else {
    $nav_links[] = "<a href=\"{$base_url}&size=large\">" . t('nav_large_photos') . "</a>";
}
$nav_links[] = lang_selector_html();
if ($using_default && $current_ym !== date('Ym')) {
    echo "<p>" . rtrim(t('aurora_showing_latest'), '.') . ': ' . t_month_year($month, $year) . ".</p>\n\n";
}

echo "<p>" . implode(" | ", $nav_links) . "</p>\n\n";

// ============================================================
// Image grid
// ============================================================

$mini_w = WebcamConfig::MINI_IMAGE_WIDTH;
$mini_h = WebcamConfig::MINI_IMAGE_HEIGHT;

$grid_class = ($size === 'large') ? 'grid-container-large' : 'grid-container';
echo "<div class=\"$grid_class\">\n";

$count = 0;
foreach ($month_images as $img) {
    $ts    = $img['timestamp']; // YYYYMMDDHHMMSS
    $score = $img['score'];

    $y  = substr($ts, 0, 4);
    $m  = substr($ts, 4, 2);
    $d  = substr($ts, 6, 2);
    $h  = substr($ts, 8, 2);
    $mi = substr($ts, 10, 2);

    $full_path = "$y/$m/$d/$ts.jpg";
    $mini_path = "$y/$m/$d/mini/$ts.jpg";
    if ($size === 'large') {
        $src = $full_path;
        $img_attrs = "";
    } else {
        $src = file_exists($mini_path) ? $mini_path : $full_path;
        $img_attrs = " width=\"$mini_w\" height=\"$mini_h\"";
    }
    $pct       = round($score * 100);
    $alt       = "Lillevik Lofoten webcam: $y-$m-$d $h:$mi – aurora {$pct}%";
    $link      = "webcam.php?type=one&image=$ts" . lang_param();
    $label     = "$d $h:$mi ({$pct}%)";

    $item_style = ($size === 'large') ? ' style="max-width:900px"' : '';
    $time_style = ($size === 'large') ? ' style="bottom:40px"' : '';
    echo "  <div class=\"grid-item\"$item_style>\n";
    echo "    <a href=\"$link\"><img alt=\"$alt\" src=\"$src\" loading=\"lazy\"{$img_attrs}></a>\n";
    echo "    <span class=\"time\"$time_style>$label</span>\n";
    echo "  </div>\n";
    $count++;
}

echo "</div>\n\n";

if ($count === 0) {
    echo '<p>(' . sprintf(t('aurora_no_photos'), t_month_year($month, $year)) . '.)</p>' . "\n\n";
}

echo "<p class=\"seo-desc\">" . t('aurora_seo_description_short') . "</p>\n\n";


// ============================================================
// Footer
// ============================================================

$prev_url_safe = $prev_url ? addslashes($prev_url) : '';
$next_url_safe = $next_url ? addslashes($next_url) : '';

echo <<<TOUCH

<!-- Touch gestures -->
<script src="https://cdn.jsdelivr.net/npm/hammerjs@2.0.8"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var body = document.body;
        var hammer = new Hammer(body);
        hammer.on('swiperight', function() { window.location.href = '$prev_url_safe'; });
        hammer.on('swipeleft',  function() { window.location.href = '$next_url_safe'; });
    });
</script>
TOUCH;


echo "<p style=\"color: rgb(200, 200, 200);\">" . t('aurora_credit') . "</p>\n\n";

echo "</body>\n</html>\n";
