<?php
/**
 * lang.php - Multilingual support for webcam gallery
 *
 * Detects visitor language from ?lang=XX query param, cookie, or Accept-Language header.
 * Provides t(string $key) for translated strings and lang_html_attr() for <html lang="">.
 *
 * Supported: en, de, it, fr, nb, nl, es, ja, zh, ko, sv, da, pl, fi, pt
 */

function detect_lang(): string {
    $supported = ['en','de','it','fr','nb','nl','es','ja','zh','ko','sv','da','pl','fi','pt'];

    // 1. Query parameter overrides everything and sets a persistent cookie
    if (isset($_GET['lang']) && in_array($_GET['lang'], $supported, true)) {
        $lang = $_GET['lang'];
        setcookie('lang', $lang, time() + 60 * 60 * 24 * 365, '/');
        return $lang;
    }

    // 2. Cookie
    if (isset($_COOKIE['lang']) && in_array($_COOKIE['lang'], $supported, true)) {
        return $_COOKIE['lang'];
    }

    // 3. Accept-Language header
    $header = $_SERVER['HTTP_ACCEPT_LANGUAGE'] ?? '';
    if ($header) {
        preg_match_all('/([a-z]{2})(?:-[a-z]{2})?(?:;q=([0-9.]+))?/i', $header, $matches, PREG_SET_ORDER);
        $best_q = 0.0;
        $best   = 'en';
        foreach ($matches as $m) {
            $tag = strtolower($m[1]);
            $q   = isset($m[2]) && $m[2] !== '' ? (float)$m[2] : 1.0;
            if ($tag === 'nn') $tag = 'nb'; // Norwegian Nynorsk → Bokmål
            if (in_array($tag, $supported, true) && $q > $best_q) {
                $best   = $tag;
                $best_q = $q;
            }
        }
        if ($best !== 'en') return $best;
    }

    return 'en';
}

function lang_html_attr(): string {
    global $LANG;
    $map = [
        'en' => 'en-US', 'de' => 'de-DE', 'it' => 'it-IT', 'fr' => 'fr-FR',
        'nb' => 'nb-NO', 'nl' => 'nl-NL', 'es' => 'es-ES', 'ja' => 'ja-JP',
        'zh' => 'zh-CN', 'ko' => 'ko-KR', 'sv' => 'sv-SE', 'da' => 'da-DK',
        'pl' => 'pl-PL', 'fi' => 'fi-FI', 'pt' => 'pt-PT',
    ];
    return $map[$LANG] ?? 'en-US';
}

/**
 * Generate <link rel="alternate" hreflang="..."> tags for all supported languages.
 * $base_url: the base URL for this page (no query string), e.g. "https://lilleviklofoten.no/webcam/"
 * English (default) gets no lang param; all others get ?lang=XX.
 */
function lang_hreflang_links(string $base_url): string {
    $langs = [
        'en' => 'en', 'de' => 'de', 'it' => 'it', 'fr' => 'fr',
        'nb' => 'nb', 'nl' => 'nl', 'es' => 'es', 'ja' => 'ja',
        'zh' => 'zh-CN', 'ko' => 'ko', 'sv' => 'sv', 'da' => 'da',
        'pl' => 'pl', 'fi' => 'fi', 'pt' => 'pt',
    ];
    $sep = strpos($base_url, '?') !== false ? '&' : '?';
    $out = '';
    foreach ($langs as $code => $hreflang) {
        $url = ($code === 'en') ? $base_url : $base_url . $sep . 'lang=' . $code;
        $out .= "  <link rel=\"alternate\" hreflang=\"$hreflang\" href=\"$url\">\n";
    }
    $out .= "  <link rel=\"alternate\" hreflang=\"x-default\" href=\"{$base_url}\">\n";
    return $out;
}

function t(string $key): string {
    global $LANG, $TRANSLATIONS;
    $val = $TRANSLATIONS[$LANG][$key] ?? $TRANSLATIONS['en'][$key] ?? $key;
    // Localise lilleviklofoten.no links for non-English languages
    if ($LANG !== 'en' && str_contains($val, 'lilleviklofoten.no')) {
        $ll = 'https://lilleviklofoten.no/' . $LANG;
        $val = str_replace(
            ['href="https://lilleviklofoten.no"', 'href="https://lilleviklofoten.no?', 'href="https://lilleviklofoten.no/webcams/'],
            ['href="' . $ll . '/"',               'href="' . $ll . '/?',              'href="' . $ll . '/webcams/'],
            $val
        );
    }
    return $val;
}

/** Returns "&lang=XX" (for appending to URLs that already have a query string), or "" for English. */
function lang_param(): string {
    global $LANG;
    return $LANG === 'en' ? '' : '&lang=' . $LANG;
}

/** Returns "?lang=XX" (for appending to bare URLs with no query string), or "" for English. */
function lang_query(): string {
    global $LANG;
    return $LANG === 'en' ? '' : '?lang=' . $LANG;
}

/** Returns the translated month name for month 1–12. */
function t_month(int $month): string {
    global $LANG, $TRANSLATIONS;
    $months = $TRANSLATIONS[$LANG]['months'] ?? $TRANSLATIONS['en']['months'];
    return $months[$month - 1] ?? '';
}

/** Returns a localised "Month Year" string, e.g. "gennaio 2026" or "2026年1月". */
function t_month_year(int $month, int $year): string {
    global $LANG;
    if ($LANG === 'ja' || $LANG === 'zh') return "{$year}年{$month}月";
    if ($LANG === 'ko') return "{$year}년 {$month}월";
    return t_month($month) . ' ' . $year;
}

/** Returns a localised "Month Day" string for navigation labels, e.g. "8 marzo" or "8. März". */
function t_month_day(int $month, int $day): string {
    global $LANG;
    $name = t_month($month);
    return match($LANG) {
        'ja', 'zh' => "{$month}月{$day}日",
        'ko'       => "{$month}월 {$day}일",
        'de', 'nb', 'da', 'fi' => "{$day}. {$name}",
        'es', 'pt' => "{$day} de {$name}",
        default    => "{$day} {$name}",
    };
}

/**
 * Returns an inline <select> language selector for the nav bar.
 * Preserves current query parameters, replacing only lang=.
 */
function lang_selector_html(): string {
    global $LANG;
    $names = [
        'en' => 'English',  'de' => 'Deutsch',    'it' => 'Italiano',  'fr' => 'Français',
        'nb' => 'Norsk',    'nl' => 'Nederlands',  'es' => 'Español',   'ja' => '日本語',
        'zh' => '中文',     'ko' => '한국어',       'sv' => 'Svenska',   'da' => 'Dansk',
        'pl' => 'Polski',   'fi' => 'Suomi',        'pt' => 'Português',
    ];
    $params = $_GET;
    unset($params['lang']);
    $qs = count($params) ? '?' . http_build_query($params) : null;

    $html = '🌐 <select class="lang-select" onchange="location.href=this.value">';
    foreach ($names as $code => $name) {
        $url      = ($qs ? $qs . '&' : '?') . 'lang=' . $code;
        $selected = $code === $LANG ? ' selected' : '';
        $html    .= '<option value="' . htmlspecialchars($url) . '"' . $selected . '>' . htmlspecialchars($name) . '</option>';
    }
    $html .= '</select>';
    return $html;
}

$LANG = detect_lang();

$TRANSLATIONS = [

// ============================================================
'en' => [
    'nav_swipe_or_use'    => 'Swipe left/right or use',
    'nav_use'             => 'Use',
    'nav_arrow_keys'      => 'the arrow keys to navigate:',
    'nav_forward'         => 'forward',
    'nav_back'            => 'back',
    'nav_up'              => 'up',
    'nav_down'            => 'down',
    'nav_and'             => 'and',
    'nav_today'           => 'Today',
    'nav_latest'          => 'Latest image',
    'nav_mini_photos'     => 'Mini photos',
    'nav_large_photos'    => 'Large photos',
    'nav_now'             => 'Now',
    'nav_entire'          => 'Entire',
    'nav_whole_day'       => 'The whole day',
    'nav_months'          => 'Months',
    'nav_and_conj'        => 'and',
    'nav_webcam'          => 'Webcam',
    'nav_aurora'          => 'Aurora borealis',
    'nav_people'          => 'People',
    'midnight_sun'        => 'Midnight sun',
    'polar_night'         => 'Polar night',
    'sunrise'             => 'Sunrise',
    'sunset'              => 'Sunset',
    'displaying_between'  => 'Displaying photos taken between %s and %s',
    'calculated_for'      => 'calculated for %s %d',
    'weather'             => 'Weather',
    'source'              => 'Source',
    'feels_like'          => 'feels like',
    'gusts'               => 'gusts',
    'max_wind'            => 'max wind',
    'no_photos'           => 'No photos to display for %s',
    'no_image_found'      => 'No image found.',
    'back_to_webcam'      => 'Back to webcam',
    'full_size'           => 'Full size',
    'prev_image'          => 'Previous',
    'next_image'          => 'Next',
    'more_photos_header'  => 'Lillevik Lofoten: More photos',
    'more_photos_intro'   => 'The photos below are taken at <a href="https://lilleviklofoten.no?utm_source=webcam">Lillevik Lofoten</a>, or nearby on Gimsøy.',
    'more_photos_booking' => 'Information and booking: <a href="https://lilleviklofoten.no?utm_source=webcam">lilleviklofoten.no</a>.',
    'more_photos_reload'  => 'For new photos: <a href="#" onclick="location.reload(); return false;">Reload</a>.',
    'made_with'           => 'Made with',
    'aurora_page_suffix'  => 'Northern lights',
    'aurora_forecast'     => 'Northern lights forecast for Lofoten',
    'aurora_tonight'      => 'Tonight',
    'aurora_tomorrow'     => 'Tomorrow night',
    'aurora_no_activity'  => 'No activity',
    'aurora_low'          => 'Low',
    'aurora_medium'       => 'Medium',
    'aurora_high'         => 'High',
    'aurora_extreme'      => 'Extreme',
    'cloud_clear'         => 'Clear',
    'cloud_few'           => 'Few clouds',
    'cloud_partly'        => 'Partly cloudy',
    'cloud_cloudy'        => 'Cloudy',
    'cloud_overcast'      => 'Overcast',
    'cloud_fog'           => 'Fog',
    'aurora_updated'      => 'updated',
    'aurora_no_photos'    => 'No northern lights photos to display for %s',
    'aurora_credit'       => 'Northern lights detection by <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">aurora_scan.py</a>. Image overlay: day, time, and aurora detection score.',
    'aurora_intro'        => '<a href=".">Webcam</a> at <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norway.',
    'aurora_see_also'     => 'See also: <a href="https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/">Northern lights at Lillevik Lofoten</a>.',
    'months'             => ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    'webcam_intro'        => '<a href=".">Webcam</a> at <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norway. See also: <a href="https://lilleviklofoten.no/webcams/">Lofoten webcams at Gimsøy, Henningsvær, Reine, Svolvær, Leknes, etc.</a>',
    'people_no_photos'    => 'No photos with people to display for %s',
    'people_credit'       => 'People detection by <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">people_scan.py</a> using YOLOv8. Image label: day, time, and detection confidence.',
],

// ============================================================
'de' => [
    'nav_swipe_or_use'    => 'Links/rechts wischen oder',
    'nav_use'             => 'Verwende',
    'nav_arrow_keys'      => 'die Pfeiltasten zur Navigation:',
    'nav_forward'         => 'vorwärts',
    'nav_back'            => 'zurück',
    'nav_up'              => 'hoch',
    'nav_down'            => 'runter',
    'nav_and'             => 'und',
    'nav_today'           => 'Heute',
    'nav_latest'          => 'Neuestes Bild',
    'nav_mini_photos'     => 'Miniaturbilder',
    'nav_large_photos'    => 'Großbilder',
    'nav_now'             => 'Jetzt',
    'nav_entire'          => 'Gesamt',
    'nav_whole_day'       => 'Ganzer Tag',
    'nav_months'          => 'Monate',
    'nav_and_conj'        => 'und',
    'nav_webcam'          => 'Webcam',
    'nav_aurora'          => 'Nordlichter',
    'nav_people'          => 'Personen',
    'midnight_sun'        => 'Mitternachtssonne',
    'polar_night'         => 'Polarnacht',
    'sunrise'             => 'Sonnenaufgang',
    'sunset'              => 'Sonnenuntergang',
    'displaying_between'  => 'Fotos zwischen %s und %s',
    'calculated_for'      => 'berechnet für %s %d',
    'weather'             => 'Wetter',
    'source'              => 'Quelle',
    'feels_like'          => 'gefühlt',
    'gusts'               => 'Böen',
    'max_wind'            => 'Windspitzen',
    'no_photos'           => 'Keine Fotos für %s',
    'no_image_found'      => 'Kein Bild gefunden.',
    'back_to_webcam'      => 'Zur Webcam',
    'full_size'           => 'Originalgröße',
    'prev_image'          => 'Vorherige',
    'next_image'          => 'Nächste',
    'more_photos_header'  => 'Lillevik Lofoten: Weitere Fotos',
    'more_photos_intro'   => 'Die Fotos unten wurden bei <a href="https://lilleviklofoten.no?utm_source=webcam">Lillevik Lofoten</a> oder in der Nähe auf Gimsøy aufgenommen.',
    'more_photos_booking' => 'Infos und Buchung: <a href="https://lilleviklofoten.no?utm_source=webcam">lilleviklofoten.no</a>.',
    'more_photos_reload'  => 'Neue Fotos: <a href="#" onclick="location.reload(); return false;">Neu laden</a>.',
    'made_with'           => 'Erstellt mit',
    'aurora_page_suffix'  => 'Nordlichter',
    'aurora_forecast'     => 'Nordlichtvorhersage für Lofoten',
    'aurora_tonight'      => 'Heute Nacht',
    'aurora_tomorrow'     => 'Morgen Nacht',
    'aurora_no_activity'  => 'Keine Aktivität',
    'aurora_low'          => 'Schwach',
    'aurora_medium'       => 'Mittel',
    'aurora_high'         => 'Stark',
    'aurora_extreme'      => 'Extrem',
    'cloud_clear'         => 'Klar',
    'cloud_few'           => 'Leicht bewölkt',
    'cloud_partly'        => 'Teilweise bewölkt',
    'cloud_cloudy'        => 'Bewölkt',
    'cloud_overcast'      => 'Bedeckt',
    'cloud_fog'           => 'Nebel',
    'aurora_updated'      => 'aktualisiert',
    'aurora_no_photos'    => 'Keine Nordlichtfotos für %s',
    'aurora_credit'       => 'Nordlichterkennung durch <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">aurora_scan.py</a>. Bildüberlagerung: Tag, Uhrzeit und Erkennungswert.',
    'aurora_intro'        => '<a href=".">Webcam</a> bei <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norwegen.',
    'aurora_see_also'     => 'Siehe auch: <a href="https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/">Nordlichter bei Lillevik Lofoten</a>.',
    'months'             => ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
    'webcam_intro'        => '<a href=".">Webcam</a> bei <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norwegen. Siehe auch: <a href="https://lilleviklofoten.no/webcams/">Lofoten-Webcams bei Gimsøy, Henningsvær, Reine, Svolvær, Leknes usw.</a>',
    'people_no_photos'    => 'Keine Personenfotos für %s',
    'people_credit'       => 'Personenerkennung durch <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">people_scan.py</a> mit YOLOv8. Beschriftung: Tag, Uhrzeit und Erkennungswert.',
],

// ============================================================
'it' => [
    'nav_swipe_or_use'    => 'Scorri o usa',
    'nav_use'             => 'Usa',
    'nav_arrow_keys'      => 'i tasti freccia per navigare:',
    'nav_forward'         => 'avanti',
    'nav_back'            => 'indietro',
    'nav_up'              => 'su',
    'nav_down'            => 'giù',
    'nav_and'             => 'e',
    'nav_today'           => 'Oggi',
    'nav_latest'          => 'Ultima immagine',
    'nav_mini_photos'     => 'Foto mini',
    'nav_large_photos'    => 'Foto grandi',
    'nav_now'             => 'Ora',
    'nav_entire'          => 'Tutto',
    'nav_whole_day'       => 'Tutta la giornata',
    'nav_months'          => 'Mesi',
    'nav_and_conj'        => 'e',
    'nav_webcam'          => 'Webcam',
    'nav_aurora'          => 'Aurora boreale',
    'nav_people'          => 'Persone',
    'midnight_sun'        => 'Sole di mezzanotte',
    'polar_night'         => 'Notte polare',
    'sunrise'             => 'Alba',
    'sunset'              => 'Tramonto',
    'displaying_between'  => 'Foto tra %s e %s',
    'calculated_for'      => 'calcolato per %s %d',
    'weather'             => 'Meteo',
    'source'              => 'Fonte',
    'feels_like'          => 'percepita',
    'gusts'               => 'raffiche',
    'max_wind'            => 'vento max',
    'no_photos'           => 'Nessuna foto per %s',
    'no_image_found'      => 'Immagine non trovata.',
    'back_to_webcam'      => 'Torna alla webcam',
    'full_size'           => 'Dimensione originale',
    'prev_image'          => 'Precedente',
    'next_image'          => 'Successiva',
    'more_photos_header'  => 'Lillevik Lofoten: Altre foto',
    'more_photos_intro'   => 'Le foto qui sotto sono state scattate a <a href="https://lilleviklofoten.no?utm_source=webcam">Lillevik Lofoten</a>, o nelle vicinanze su Gimsøy.',
    'more_photos_booking' => 'Info e prenotazioni: <a href="https://lilleviklofoten.no?utm_source=webcam">lilleviklofoten.no</a>.',
    'more_photos_reload'  => 'Nuove foto: <a href="#" onclick="location.reload(); return false;">Aggiorna</a>.',
    'made_with'           => 'Creato con',
    'aurora_page_suffix'  => 'Aurora boreale',
    'aurora_forecast'     => 'Previsioni aurora per Lofoten',
    'aurora_tonight'      => 'Stanotte',
    'aurora_tomorrow'     => 'Domani notte',
    'aurora_no_activity'  => 'Nessuna attività',
    'aurora_low'          => 'Bassa',
    'aurora_medium'       => 'Media',
    'aurora_high'         => 'Alta',
    'aurora_extreme'      => 'Estrema',
    'cloud_clear'         => 'Sereno',
    'cloud_few'           => 'Poco nuvoloso',
    'cloud_partly'        => 'Parzialmente nuvoloso',
    'cloud_cloudy'        => 'Nuvoloso',
    'cloud_overcast'      => 'Coperto',
    'cloud_fog'           => 'Nebbia',
    'aurora_updated'      => 'aggiornato',
    'aurora_no_photos'    => 'Nessuna foto di aurora per %s',
    'aurora_credit'       => 'Rilevamento aurora da <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">aurora_scan.py</a>. Sovrapposizione: giorno, ora e punteggio.',
    'aurora_intro'        => '<a href=".">Webcam</a> a <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norvegia.',
    'aurora_see_also'     => 'Vedi anche: <a href="https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/">Aurora boreale a Lillevik Lofoten</a>.',
    'months'             => ['gennaio', 'febbraio', 'marzo', 'aprile', 'maggio', 'giugno', 'luglio', 'agosto', 'settembre', 'ottobre', 'novembre', 'dicembre'],
    'webcam_intro'        => '<a href=".">Webcam</a> a <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norvegia. Vedi anche: <a href="https://lilleviklofoten.no/webcams/">Webcam delle Lofoten a Gimsøy, Henningsvær, Reine, Svolvær, Leknes, ecc.</a>',
    'people_no_photos'    => 'Nessuna foto con persone per %s',
    'people_credit'       => 'Rilevamento persone da <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">people_scan.py</a> con YOLOv8. Etichetta: giorno, ora e confidenza.',
],

// ============================================================
'fr' => [
    'nav_swipe_or_use'    => 'Faites glisser ou utilisez',
    'nav_use'             => 'Utilisez',
    'nav_arrow_keys'      => 'les touches fléchées pour naviguer\u00a0:',
    'nav_forward'         => 'suivant',
    'nav_back'            => 'précédent',
    'nav_up'              => 'haut',
    'nav_down'            => 'bas',
    'nav_and'             => 'et',
    'nav_today'           => "Aujourd'hui",
    'nav_latest'          => 'Dernière image',
    'nav_mini_photos'     => 'Petites photos',
    'nav_large_photos'    => 'Grandes photos',
    'nav_now'             => 'Maintenant',
    'nav_entire'          => 'Tout',
    'nav_whole_day'       => 'Toute la journée',
    'nav_months'          => 'Mois',
    'nav_and_conj'        => 'et',
    'nav_webcam'          => 'Webcam',
    'nav_aurora'          => 'Aurore boréale',
    'nav_people'          => 'Personnes',
    'midnight_sun'        => 'Soleil de minuit',
    'polar_night'         => 'Nuit polaire',
    'sunrise'             => 'Lever du soleil',
    'sunset'              => 'Coucher du soleil',
    'displaying_between'  => 'Photos entre %s et %s',
    'calculated_for'      => 'calculé pour %s %d',
    'weather'             => 'Météo',
    'source'              => 'Source',
    'feels_like'          => 'ressenti',
    'gusts'               => 'rafales',
    'max_wind'            => 'vent max',
    'no_photos'           => 'Aucune photo pour %s',
    'no_image_found'      => 'Image introuvable.',
    'back_to_webcam'      => 'Retour à la webcam',
    'full_size'           => 'Taille originale',
    'prev_image'          => 'Précédente',
    'next_image'          => 'Suivante',
    'more_photos_header'  => 'Lillevik Lofoten\u00a0: Plus de photos',
    'more_photos_intro'   => 'Les photos ci-dessous sont prises à <a href="https://lilleviklofoten.no?utm_source=webcam">Lillevik Lofoten</a>, ou à proximité sur Gimsøy.',
    'more_photos_booking' => 'Infos et réservations\u00a0: <a href="https://lilleviklofoten.no?utm_source=webcam">lilleviklofoten.no</a>.',
    'more_photos_reload'  => 'Nouvelles photos\u00a0: <a href="#" onclick="location.reload(); return false;">Actualiser</a>.',
    'made_with'           => 'Généré par',
    'aurora_page_suffix'  => 'Aurore boréale',
    'aurora_forecast'     => 'Prévisions aurores pour Lofoten',
    'aurora_tonight'      => 'Ce soir',
    'aurora_tomorrow'     => 'Demain soir',
    'aurora_no_activity'  => "Pas d'activité",
    'aurora_low'          => 'Faible',
    'aurora_medium'       => 'Moyenne',
    'aurora_high'         => 'Forte',
    'aurora_extreme'      => 'Extrême',
    'cloud_clear'         => 'Dégagé',
    'cloud_few'           => 'Peu nuageux',
    'cloud_partly'        => 'Partiellement nuageux',
    'cloud_cloudy'        => 'Nuageux',
    'cloud_overcast'      => 'Couvert',
    'cloud_fog'           => 'Brouillard',
    'aurora_updated'      => 'mis à jour',
    'aurora_no_photos'    => "Aucune photo d'aurore pour %s",
    'aurora_credit'       => "Détection d'aurores par <a style=\"color: rgb(200, 200, 200);\" href=\"https://github.com/cloveras/webcam\">aurora_scan.py</a>. Superposition\u00a0: jour, heure et score.",
    'aurora_intro'        => '<a href=".">Webcam</a> à <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norvège.',
    'aurora_see_also'     => 'Voir aussi : <a href="https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/">Aurore boréale à Lillevik Lofoten</a>.',
    'months'             => ['janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre'],
    'webcam_intro'        => '<a href=".">Webcam</a> à <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norvège. Voir aussi : <a href="https://lilleviklofoten.no/webcams/">Webcams des Lofoten à Gimsøy, Henningsvær, Reine, Svolvær, Leknes, etc.</a>',
    'people_no_photos'    => 'Aucune photo avec des personnes pour %s',
    'people_credit'       => 'Détection de personnes par <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">people_scan.py</a> avec YOLOv8. Étiquette\u00a0: jour, heure et confiance.',
],

// ============================================================
'nb' => [
    'nav_swipe_or_use'    => 'Sveip eller bruk',
    'nav_use'             => 'Bruk',
    'nav_arrow_keys'      => 'piltastene for å navigere:',
    'nav_forward'         => 'fremover',
    'nav_back'            => 'tilbake',
    'nav_up'              => 'opp',
    'nav_down'            => 'ned',
    'nav_and'             => 'og',
    'nav_today'           => 'I dag',
    'nav_latest'          => 'Siste bilde',
    'nav_mini_photos'     => 'Miniatyrbilder',
    'nav_large_photos'    => 'Store bilder',
    'nav_now'             => 'Nå',
    'nav_entire'          => 'Hele',
    'nav_whole_day'       => 'Hele dagen',
    'nav_months'          => 'Måneder',
    'nav_and_conj'        => 'og',
    'nav_webcam'          => 'Webkamera',
    'nav_aurora'          => 'Nordlys',
    'nav_people'          => 'Personer',
    'midnight_sun'        => 'Midnattssol',
    'polar_night'         => 'Mørketid',
    'sunrise'             => 'Soloppgang',
    'sunset'              => 'Solnedgang',
    'displaying_between'  => 'Bilder tatt mellom %s og %s',
    'calculated_for'      => 'beregnet for %s %d',
    'weather'             => 'Vær',
    'source'              => 'Kilde',
    'feels_like'          => 'føles som',
    'gusts'               => 'kast',
    'max_wind'            => 'maks vind',
    'no_photos'           => 'Ingen bilder for %s',
    'no_image_found'      => 'Fant ingen bilde.',
    'back_to_webcam'      => 'Tilbake til kamera',
    'full_size'           => 'Full størrelse',
    'prev_image'          => 'Forrige',
    'next_image'          => 'Neste',
    'more_photos_header'  => 'Lillevik Lofoten: Flere bilder',
    'more_photos_intro'   => 'Bildene nedenfor er tatt ved <a href="https://lilleviklofoten.no?utm_source=webcam">Lillevik Lofoten</a>, eller i nærheten på Gimsøy.',
    'more_photos_booking' => 'Informasjon og booking: <a href="https://lilleviklofoten.no?utm_source=webcam">lilleviklofoten.no</a>.',
    'more_photos_reload'  => 'For nye bilder: <a href="#" onclick="location.reload(); return false;">Last inn på nytt</a>.',
    'made_with'           => 'Laget med',
    'aurora_page_suffix'  => 'Nordlys',
    'aurora_forecast'     => 'Nordlysvarsel for Lofoten',
    'aurora_tonight'      => 'I natt',
    'aurora_tomorrow'     => 'Neste natt',
    'aurora_no_activity'  => 'Ingen aktivitet',
    'aurora_low'          => 'Lav',
    'aurora_medium'       => 'Middels',
    'aurora_high'         => 'Høy',
    'aurora_extreme'      => 'Ekstrem',
    'cloud_clear'         => 'Klart',
    'cloud_few'           => 'Lettskyet',
    'cloud_partly'        => 'Delvis skyet',
    'cloud_cloudy'        => 'Skyet',
    'cloud_overcast'      => 'Overskyet',
    'cloud_fog'           => 'Tåke',
    'aurora_updated'      => 'oppdatert',
    'aurora_no_photos'    => 'Ingen nordlysbilder for %s',
    'aurora_credit'       => 'Nordlysregistrering av <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">aurora_scan.py</a>. Bildetekst: dag, tid og poengsum.',
    'aurora_intro'        => '<a href=".">Webkamera</a> ved <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norge.',
    'aurora_see_also'     => 'Se også: <a href="https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/">Nordlys ved Lillevik Lofoten</a>.',
    'months'             => ['januar', 'februar', 'mars', 'april', 'mai', 'juni', 'juli', 'august', 'september', 'oktober', 'november', 'desember'],
    'webcam_intro'        => '<a href=".">Webkamera</a> ved <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norge. Se også: <a href="https://lilleviklofoten.no/webcams/">Lofoten-webkameraer ved Gimsøy, Henningsvær, Reine, Svolvær, Leknes m.fl.</a>',
    'people_no_photos'    => 'Ingen personbilder for %s',
    'people_credit'       => 'Personregistrering av <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">people_scan.py</a> med YOLOv8. Bildetekst: dag, tid og konfidensverdi.',
],

// ============================================================
'nl' => [
    'nav_swipe_or_use'    => 'Veeg links/rechts of gebruik',
    'nav_use'             => 'Gebruik',
    'nav_arrow_keys'      => 'de pijltjestoetsen om te navigeren:',
    'nav_forward'         => 'vooruit',
    'nav_back'            => 'terug',
    'nav_up'              => 'omhoog',
    'nav_down'            => 'omlaag',
    'nav_and'             => 'en',
    'nav_today'           => 'Vandaag',
    'nav_latest'          => "Laatste afbeelding",
    'nav_mini_photos'     => "Minifoto's",
    'nav_large_photos'    => "Grote foto's",
    'nav_now'             => 'Nu',
    'nav_entire'          => 'Geheel',
    'nav_whole_day'       => 'Hele dag',
    'nav_months'          => 'Maanden',
    'nav_and_conj'        => 'en',
    'nav_webcam'          => 'Webcam',
    'nav_aurora'          => 'Noorderlicht',
    'nav_people'          => 'Personen',
    'midnight_sun'        => 'Middernachtszon',
    'polar_night'         => 'Poolnacht',
    'sunrise'             => 'Zonsopgang',
    'sunset'              => 'Zonsondergang',
    'displaying_between'  => "Foto's tussen %s en %s",
    'calculated_for'      => 'berekend voor %s %d',
    'weather'             => 'Weer',
    'source'              => 'Bron',
    'feels_like'          => 'gevoelstemperatuur',
    'gusts'               => 'windstoten',
    'max_wind'            => 'max. wind',
    'no_photos'           => "Geen foto's voor %s",
    'no_image_found'      => 'Geen afbeelding gevonden.',
    'back_to_webcam'      => 'Terug naar webcam',
    'full_size'           => 'Volledige grootte',
    'prev_image'          => 'Vorige',
    'next_image'          => 'Volgende',
    'more_photos_header'  => "Lillevik Lofoten: Meer foto's",
    'more_photos_intro'   => 'De foto\'s hieronder zijn gemaakt bij <a href="https://lilleviklofoten.no?utm_source=webcam">Lillevik Lofoten</a>, of in de buurt op Gimsøy.',
    'more_photos_booking' => 'Informatie en boeken: <a href="https://lilleviklofoten.no?utm_source=webcam">lilleviklofoten.no</a>.',
    'more_photos_reload'  => "Nieuwe foto's: <a href=\"#\" onclick=\"location.reload(); return false;\">Herladen</a>.",
    'made_with'           => 'Gemaakt met',
    'aurora_page_suffix'  => 'Noorderlicht',
    'aurora_forecast'     => 'Noorderlichtvoorspelling voor Lofoten',
    'aurora_tonight'      => 'Vanavond',
    'aurora_tomorrow'     => 'Morgenavond',
    'aurora_no_activity'  => 'Geen activiteit',
    'aurora_low'          => 'Laag',
    'aurora_medium'       => 'Gemiddeld',
    'aurora_high'         => 'Hoog',
    'aurora_extreme'      => 'Extreem',
    'cloud_clear'         => 'Helder',
    'cloud_few'           => 'Licht bewolkt',
    'cloud_partly'        => 'Gedeeltelijk bewolkt',
    'cloud_cloudy'        => 'Bewolkt',
    'cloud_overcast'      => 'Zwaar bewolkt',
    'cloud_fog'           => 'Mist',
    'aurora_updated'      => 'bijgewerkt',
    'aurora_no_photos'    => "Geen noorderlichtfoto's voor %s",
    'aurora_credit'       => 'Noorderlichtdetectie door <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">aurora_scan.py</a>. Beeldoverlay: dag, tijd en detectiescore.',
    'aurora_intro'        => '<a href=".">Webcam</a> bij <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Noorwegen.',
    'aurora_see_also'     => 'Zie ook: <a href="https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/">Noorderlicht bij Lillevik Lofoten</a>.',
    'months'             => ['januari', 'februari', 'maart', 'april', 'mei', 'juni', 'juli', 'augustus', 'september', 'oktober', 'november', 'december'],
    'webcam_intro'        => '<a href=".">Webcam</a> bij <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Noorwegen. Zie ook: <a href="https://lilleviklofoten.no/webcams/">Lofoten-webcams bij Gimsøy, Henningsvær, Reine, Svolvær, Leknes, enz.</a>',
    'people_no_photos'    => "Geen foto's met personen voor %s",
    'people_credit'       => "Persoonsdetectie door <a style=\"color: rgb(200, 200, 200);\" href=\"https://github.com/cloveras/webcam\">people_scan.py</a> met YOLOv8. Label: dag, tijd en betrouwbaarheid.",
],

// ============================================================
'es' => [
    'nav_swipe_or_use'    => 'Desliza o usa',
    'nav_use'             => 'Usa',
    'nav_arrow_keys'      => 'las teclas de flecha para navegar:',
    'nav_forward'         => 'adelante',
    'nav_back'            => 'atrás',
    'nav_up'              => 'arriba',
    'nav_down'            => 'abajo',
    'nav_and'             => 'y',
    'nav_today'           => 'Hoy',
    'nav_latest'          => 'Última imagen',
    'nav_mini_photos'     => 'Fotos pequeñas',
    'nav_large_photos'    => 'Fotos grandes',
    'nav_now'             => 'Ahora',
    'nav_entire'          => 'Todo',
    'nav_whole_day'       => 'Todo el día',
    'nav_months'          => 'Meses',
    'nav_and_conj'        => 'y',
    'nav_webcam'          => 'Webcam',
    'nav_aurora'          => 'Aurora boreal',
    'nav_people'          => 'Personas',
    'midnight_sun'        => 'Sol de medianoche',
    'polar_night'         => 'Noche polar',
    'sunrise'             => 'Amanecer',
    'sunset'              => 'Atardecer',
    'displaying_between'  => 'Fotos entre %s y %s',
    'calculated_for'      => 'calculado para %s %d',
    'weather'             => 'Tiempo',
    'source'              => 'Fuente',
    'feels_like'          => 'sensación',
    'gusts'               => 'ráfagas',
    'max_wind'            => 'viento máx.',
    'no_photos'           => 'Sin fotos para %s',
    'no_image_found'      => 'Imagen no encontrada.',
    'back_to_webcam'      => 'Volver a la webcam',
    'full_size'           => 'Tamaño original',
    'prev_image'          => 'Anterior',
    'next_image'          => 'Siguiente',
    'more_photos_header'  => 'Lillevik Lofoten: Más fotos',
    'more_photos_intro'   => 'Las fotos de abajo están tomadas en <a href="https://lilleviklofoten.no?utm_source=webcam">Lillevik Lofoten</a>, o cerca en Gimsøy.',
    'more_photos_booking' => 'Info y reservas: <a href="https://lilleviklofoten.no?utm_source=webcam">lilleviklofoten.no</a>.',
    'more_photos_reload'  => 'Nuevas fotos: <a href="#" onclick="location.reload(); return false;">Actualizar</a>.',
    'made_with'           => 'Creado con',
    'aurora_page_suffix'  => 'Aurora boreal',
    'aurora_forecast'     => 'Pronóstico de auroras para Lofoten',
    'aurora_tonight'      => 'Esta noche',
    'aurora_tomorrow'     => 'Mañana por la noche',
    'aurora_no_activity'  => 'Sin actividad',
    'aurora_low'          => 'Baja',
    'aurora_medium'       => 'Media',
    'aurora_high'         => 'Alta',
    'aurora_extreme'      => 'Extrema',
    'cloud_clear'         => 'Despejado',
    'cloud_few'           => 'Poco nublado',
    'cloud_partly'        => 'Parcialmente nublado',
    'cloud_cloudy'        => 'Nublado',
    'cloud_overcast'      => 'Cubierto',
    'cloud_fog'           => 'Niebla',
    'aurora_updated'      => 'actualizado',
    'aurora_no_photos'    => 'Sin fotos de aurora para %s',
    'aurora_credit'       => 'Detección de auroras por <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">aurora_scan.py</a>. Superposición: día, hora y puntuación.',
    'aurora_intro'        => '<a href=".">Webcam</a> en <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Noruega.',
    'aurora_see_also'     => 'Ver también: <a href="https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/">Aurora boreal en Lillevik Lofoten</a>.',
    'months'             => ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'],
    'webcam_intro'        => '<a href=".">Webcam</a> en <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Noruega. Ver también: <a href="https://lilleviklofoten.no/webcams/">Webcams de Lofoten en Gimsøy, Henningsvær, Reine, Svolvær, Leknes, etc.</a>',
    'people_no_photos'    => 'Sin fotos con personas para %s',
    'people_credit'       => 'Detección de personas por <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">people_scan.py</a> con YOLOv8. Etiqueta: día, hora y confianza.',
],

// ============================================================
'ja' => [
    'nav_swipe_or_use'    => '左右にスワイプするか',
    'nav_use'             => '使用：',
    'nav_arrow_keys'      => '矢印キーでナビゲート：',
    'nav_forward'         => '次へ',
    'nav_back'            => '前へ',
    'nav_up'              => '上',
    'nav_down'            => '下',
    'nav_and'             => '、',
    'nav_today'           => '今日',
    'nav_latest'          => '最新画像',
    'nav_mini_photos'     => 'ミニ写真',
    'nav_large_photos'    => '大きい写真',
    'nav_now'             => '現在',
    'nav_entire'          => '全体',
    'nav_whole_day'       => '1日全体',
    'nav_months'          => '月',
    'nav_and_conj'        => 'と',
    'nav_webcam'          => 'ウェブカメラ',
    'nav_aurora'          => 'オーロラ',
    'nav_people'          => '人物',
    'midnight_sun'        => '白夜',
    'polar_night'         => '極夜',
    'sunrise'             => '日の出',
    'sunset'              => '日の入り',
    'displaying_between'  => '%sから%sの写真',
    'calculated_for'      => '%s%d日の計算値',
    'weather'             => '天気',
    'source'              => '情報源',
    'feels_like'          => '体感',
    'gusts'               => '突風',
    'max_wind'            => '最大風速',
    'no_photos'           => '%sの写真なし',
    'no_image_found'      => '画像が見つかりません。',
    'back_to_webcam'      => 'ウェブカメラに戻る',
    'full_size'           => '原寸大',
    'prev_image'          => '前の画像',
    'next_image'          => '次の画像',
    'more_photos_header'  => 'リレビック・ロフォーテン：その他の写真',
    'more_photos_intro'   => '以下の写真は<a href="https://lilleviklofoten.no?utm_source=webcam">Lillevik Lofoten</a>またはGimsøy周辺で撮影されたものです。',
    'more_photos_booking' => '情報・予約：<a href="https://lilleviklofoten.no?utm_source=webcam">lilleviklofoten.no</a>。',
    'more_photos_reload'  => '新しい写真：<a href="#" onclick="location.reload(); return false;">再読み込み</a>。',
    'made_with'           => '使用ツール：',
    'aurora_page_suffix'  => 'オーロラ',
    'aurora_forecast'     => 'ロフォーテンのオーロラ予報',
    'aurora_tonight'      => '今夜',
    'aurora_tomorrow'     => '明日の夜',
    'aurora_no_activity'  => '活動なし',
    'aurora_low'          => '弱い',
    'aurora_medium'       => '中程度',
    'aurora_high'         => '強い',
    'aurora_extreme'      => '極めて強い',
    'cloud_clear'         => '快晴',
    'cloud_few'           => '少し曇り',
    'cloud_partly'        => '一部曇り',
    'cloud_cloudy'        => '曇り',
    'cloud_overcast'      => '全曇り',
    'cloud_fog'           => '霧',
    'aurora_updated'      => '更新',
    'aurora_no_photos'    => '%sのオーロラ写真なし',
    'aurora_credit'       => '<a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">aurora_scan.py</a>によるオーロラ検出。ラベル：日付、時刻、スコア。',
    'aurora_intro'        => '<a href="https://lilleviklofoten.no">Lillevik Lofoten</a>（ノルウェー、ロフォーテン諸島、Gimsøy、Vik）の<a href=".">ウェブカメラ</a>。',
    'aurora_see_also'     => '関連： <a href="https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/">Lillevik Lofoten のオーロラ</a>。',
    'months'             => ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    'webcam_intro'        => '<a href="https://lilleviklofoten.no">Lillevik Lofoten</a>（ノルウェー、ロフォーテン諸島、Gimsøy、Vik）の<a href=".">ウェブカメラ</a>。関連: <a href="https://lilleviklofoten.no/webcams/">Gimsøy、Henningsvær、Reine、Svolvær、Leknesのロフォーテンウェブカメラ</a>。',
    'people_no_photos'    => '%sの人物写真なし',
    'people_credit'       => 'YOLOv8を使用した<a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">people_scan.py</a>による人物検出。ラベル：日付、時刻、信頼度。',
],

// ============================================================
'zh' => [
    'nav_swipe_or_use'    => '左右滑动或使用',
    'nav_use'             => '使用',
    'nav_arrow_keys'      => '方向键导航：',
    'nav_forward'         => '下一张',
    'nav_back'            => '上一张',
    'nav_up'              => '上',
    'nav_down'            => '下',
    'nav_and'             => '和',
    'nav_today'           => '今天',
    'nav_latest'          => '最新图片',
    'nav_mini_photos'     => '缩略图',
    'nav_large_photos'    => '大图',
    'nav_now'             => '当前',
    'nav_entire'          => '完整',
    'nav_whole_day'       => '全天',
    'nav_months'          => '月份',
    'nav_and_conj'        => '和',
    'nav_webcam'          => '网络摄像头',
    'nav_aurora'          => '北极光',
    'nav_people'          => '人物',
    'midnight_sun'        => '极昼',
    'polar_night'         => '极夜',
    'sunrise'             => '日出',
    'sunset'              => '日落',
    'displaying_between'  => '%s至%s的照片',
    'calculated_for'      => '%s%d日计算值',
    'weather'             => '天气',
    'source'              => '来源',
    'feels_like'          => '体感',
    'gusts'               => '阵风',
    'max_wind'            => '最大风速',
    'no_photos'           => '%s无照片',
    'no_image_found'      => '未找到图片。',
    'back_to_webcam'      => '返回摄像头',
    'full_size'           => '原始尺寸',
    'prev_image'          => '上一张',
    'next_image'          => '下一张',
    'more_photos_header'  => '利勒维克罗弗敦：更多照片',
    'more_photos_intro'   => '以下照片拍摄于<a href="https://lilleviklofoten.no?utm_source=webcam">Lillevik Lofoten</a>或Gimsøy附近。',
    'more_photos_booking' => '信息与预订：<a href="https://lilleviklofoten.no?utm_source=webcam">lilleviklofoten.no</a>。',
    'more_photos_reload'  => '查看新照片：<a href="#" onclick="location.reload(); return false;">刷新</a>。',
    'made_with'           => '由以下工具生成：',
    'aurora_page_suffix'  => '北极光',
    'aurora_forecast'     => '罗弗敦极光预报',
    'aurora_tonight'      => '今晚',
    'aurora_tomorrow'     => '明晚',
    'aurora_no_activity'  => '无活动',
    'aurora_low'          => '弱',
    'aurora_medium'       => '中等',
    'aurora_high'         => '强',
    'aurora_extreme'      => '极强',
    'cloud_clear'         => '晴朗',
    'cloud_few'           => '少云',
    'cloud_partly'        => '多云',
    'cloud_cloudy'        => '阴',
    'cloud_overcast'      => '阴天',
    'cloud_fog'           => '雾',
    'aurora_updated'      => '更新于',
    'aurora_no_photos'    => '%s无极光照片',
    'aurora_credit'       => '<a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">aurora_scan.py</a>极光检测。标注：日期、时间和分数。',
    'aurora_intro'        => '<a href=".">网络摄像头</a>位于<a href="https://lilleviklofoten.no">Lillevik Lofoten</a>，挪威罗弗敦群岛Gimsøy岛Vik。',
    'aurora_see_also'     => '另请参阅： <a href="https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/">Lillevik Lofoten 的极光</a>。',
    'months'             => ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    'webcam_intro'        => '<a href=".">网络摄像头</a>位于<a href="https://lilleviklofoten.no">Lillevik Lofoten</a>，挪威罗弗敦群岛Gimsøy岛Vik。另请参阅：<a href="https://lilleviklofoten.no/webcams/">罗弗敦各地摄像头（Gimsøy、Henningsvær、Reine、Svolvær、Leknes等）</a>。',
    'people_no_photos'    => '%s无人物照片',
    'people_credit'       => '<a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">people_scan.py</a>使用YOLOv8进行人物检测。标注：日期、时间和置信度。',
],

// ============================================================
'ko' => [
    'nav_swipe_or_use'    => '좌우로 스와이프하거나',
    'nav_use'             => '사용:',
    'nav_arrow_keys'      => '방향키로 탐색:',
    'nav_forward'         => '다음',
    'nav_back'            => '이전',
    'nav_up'              => '위',
    'nav_down'            => '아래',
    'nav_and'             => '및',
    'nav_today'           => '오늘',
    'nav_latest'          => '최신 이미지',
    'nav_mini_photos'     => '작은 사진',
    'nav_large_photos'    => '큰 사진',
    'nav_now'             => '현재',
    'nav_entire'          => '전체',
    'nav_whole_day'       => '하루 전체',
    'nav_months'          => '월',
    'nav_and_conj'        => '및',
    'nav_webcam'          => '웹캠',
    'nav_aurora'          => '오로라',
    'nav_people'          => '사람',
    'midnight_sun'        => '백야',
    'polar_night'         => '극야',
    'sunrise'             => '일출',
    'sunset'              => '일몰',
    'displaying_between'  => '%s~%s 사진',
    'calculated_for'      => '%s %d일 기준',
    'weather'             => '날씨',
    'source'              => '출처',
    'feels_like'          => '체감',
    'gusts'               => '돌풍',
    'max_wind'            => '최대풍속',
    'no_photos'           => '%s 사진 없음',
    'no_image_found'      => '이미지를 찾을 수 없습니다.',
    'back_to_webcam'      => '웹캠으로 돌아가기',
    'full_size'           => '원본 크기',
    'prev_image'          => '이전 이미지',
    'next_image'          => '다음 이미지',
    'more_photos_header'  => 'Lillevik Lofoten: 더 많은 사진',
    'more_photos_intro'   => '아래 사진들은 <a href="https://lilleviklofoten.no?utm_source=webcam">Lillevik Lofoten</a> 또는 Gimsøy 근처에서 촬영된 것입니다.',
    'more_photos_booking' => '정보 및 예약: <a href="https://lilleviklofoten.no?utm_source=webcam">lilleviklofoten.no</a>.',
    'more_photos_reload'  => '새 사진: <a href="#" onclick="location.reload(); return false;">새로고침</a>.',
    'made_with'           => '제작:',
    'aurora_page_suffix'  => '오로라',
    'aurora_forecast'     => '로포텐 오로라 예보',
    'aurora_tonight'      => '오늘 밤',
    'aurora_tomorrow'     => '내일 밤',
    'aurora_no_activity'  => '활동 없음',
    'aurora_low'          => '약함',
    'aurora_medium'       => '보통',
    'aurora_high'         => '강함',
    'aurora_extreme'      => '극강',
    'cloud_clear'         => '맑음',
    'cloud_few'           => '구름 조금',
    'cloud_partly'        => '구름 많음',
    'cloud_cloudy'        => '흐림',
    'cloud_overcast'      => '완전 흐림',
    'cloud_fog'           => '안개',
    'aurora_updated'      => '업데이트',
    'aurora_no_photos'    => '%s 오로라 사진 없음',
    'aurora_credit'       => '<a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">aurora_scan.py</a>로 오로라 감지. 레이블: 날짜, 시간, 점수.',
    'aurora_intro'        => '노르웨이 로포텐 제도 Gimsøy, Vik의 <a href="https://lilleviklofoten.no">Lillevik Lofoten</a> <a href=".">웹카메라</a>.',
    'aurora_see_also'     => '참고： <a href="https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/">Lillevik Lofoten의 오로라</a>.',
    'months'             => ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    'webcam_intro'        => '노르웨이 로포텐 제도 Gimsøy, Vik의 <a href="https://lilleviklofoten.no">Lillevik Lofoten</a> <a href=".">웹카메라</a>. 참고: <a href="https://lilleviklofoten.no/webcams/">Gimsøy, Henningsvær, Reine, Svolvær, Leknes 등 로포텐 웹카메라</a>.',
    'people_no_photos'    => '%s 인물 사진 없음',
    'people_credit'       => 'YOLOv8을 사용한 <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">people_scan.py</a>로 인물 감지. 레이블: 날짜, 시간, 신뢰도.',
],

// ============================================================
'sv' => [
    'nav_swipe_or_use'    => 'Svep eller använd',
    'nav_use'             => 'Använd',
    'nav_arrow_keys'      => 'piltangenterna för att navigera:',
    'nav_forward'         => 'framåt',
    'nav_back'            => 'bakåt',
    'nav_up'              => 'upp',
    'nav_down'            => 'ner',
    'nav_and'             => 'och',
    'nav_today'           => 'Idag',
    'nav_latest'          => 'Senaste bild',
    'nav_mini_photos'     => 'Minibilder',
    'nav_large_photos'    => 'Stora bilder',
    'nav_now'             => 'Nu',
    'nav_entire'          => 'Hela',
    'nav_whole_day'       => 'Hela dagen',
    'nav_months'          => 'Månader',
    'nav_and_conj'        => 'och',
    'nav_webcam'          => 'Webbkamera',
    'nav_aurora'          => 'Norrsken',
    'nav_people'          => 'Personer',
    'midnight_sun'        => 'Midnattssol',
    'polar_night'         => 'Polarnatt',
    'sunrise'             => 'Soluppgång',
    'sunset'              => 'Solnedgång',
    'displaying_between'  => 'Foton mellan %s och %s',
    'calculated_for'      => 'beräknat för %s %d',
    'weather'             => 'Väder',
    'source'              => 'Källa',
    'feels_like'          => 'känns som',
    'gusts'               => 'vindbyar',
    'max_wind'            => 'max vind',
    'no_photos'           => 'Inga foton för %s',
    'no_image_found'      => 'Ingen bild hittades.',
    'back_to_webcam'      => 'Tillbaka till webbkameran',
    'full_size'           => 'Fullstorlek',
    'prev_image'          => 'Föregående',
    'next_image'          => 'Nästa',
    'more_photos_header'  => 'Lillevik Lofoten: Fler foton',
    'more_photos_intro'   => 'Bilderna nedan är tagna vid <a href="https://lilleviklofoten.no?utm_source=webcam">Lillevik Lofoten</a>, eller i närheten på Gimsøy.',
    'more_photos_booking' => 'Information och bokning: <a href="https://lilleviklofoten.no?utm_source=webcam">lilleviklofoten.no</a>.',
    'more_photos_reload'  => 'Nya foton: <a href="#" onclick="location.reload(); return false;">Ladda om</a>.',
    'made_with'           => 'Skapad med',
    'aurora_page_suffix'  => 'Norrsken',
    'aurora_forecast'     => 'Norrskensvarsel för Lofoten',
    'aurora_tonight'      => 'I natt',
    'aurora_tomorrow'     => 'Imorgon natt',
    'aurora_no_activity'  => 'Ingen aktivitet',
    'aurora_low'          => 'Låg',
    'aurora_medium'       => 'Medel',
    'aurora_high'         => 'Hög',
    'aurora_extreme'      => 'Extrem',
    'cloud_clear'         => 'Klart',
    'cloud_few'           => 'Lätt molnigt',
    'cloud_partly'        => 'Delvis molnigt',
    'cloud_cloudy'        => 'Molnigt',
    'cloud_overcast'      => 'Mulet',
    'cloud_fog'           => 'Dimma',
    'aurora_updated'      => 'uppdaterad',
    'aurora_no_photos'    => 'Inga norrskensbilder för %s',
    'aurora_credit'       => 'Norrskensdetektion av <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">aurora_scan.py</a>. Bildtext: dag, tid och poäng.',
    'aurora_intro'        => '<a href=".">Webbkamera</a> vid <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norge.',
    'aurora_see_also'     => 'Se även: <a href="https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/">Norrsken vid Lillevik Lofoten</a>.',
    'months'             => ['januari', 'februari', 'mars', 'april', 'maj', 'juni', 'juli', 'augusti', 'september', 'oktober', 'november', 'december'],
    'webcam_intro'        => '<a href=".">Webbkamera</a> vid <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norge. Se även: <a href="https://lilleviklofoten.no/webcams/">Lofoten-webbkameror vid Gimsøy, Henningsvær, Reine, Svolvær, Leknes m.fl.</a>',
    'people_no_photos'    => 'Inga personbilder för %s',
    'people_credit'       => 'Persondetektering av <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">people_scan.py</a> med YOLOv8. Etikett: dag, tid och säkerhet.',
],

// ============================================================
'da' => [
    'nav_swipe_or_use'    => 'Stryg eller brug',
    'nav_use'             => 'Brug',
    'nav_arrow_keys'      => 'piletasterne til at navigere:',
    'nav_forward'         => 'frem',
    'nav_back'            => 'tilbage',
    'nav_up'              => 'op',
    'nav_down'            => 'ned',
    'nav_and'             => 'og',
    'nav_today'           => 'I dag',
    'nav_latest'          => 'Seneste billede',
    'nav_mini_photos'     => 'Minimalbilleder',
    'nav_large_photos'    => 'Store billeder',
    'nav_now'             => 'Nu',
    'nav_entire'          => 'Hele',
    'nav_whole_day'       => 'Hele dagen',
    'nav_months'          => 'Måneder',
    'nav_and_conj'        => 'og',
    'nav_webcam'          => 'Webkamera',
    'nav_aurora'          => 'Nordlys',
    'nav_people'          => 'Personer',
    'midnight_sun'        => 'Midnatssol',
    'polar_night'         => 'Polarnat',
    'sunrise'             => 'Solopgang',
    'sunset'              => 'Solnedgang',
    'displaying_between'  => 'Billeder mellem %s og %s',
    'calculated_for'      => 'beregnet for %s %d',
    'weather'             => 'Vejr',
    'source'              => 'Kilde',
    'feels_like'          => 'føles som',
    'gusts'               => 'vindstød',
    'max_wind'            => 'maks. vind',
    'no_photos'           => 'Ingen billeder for %s',
    'no_image_found'      => 'Intet billede fundet.',
    'back_to_webcam'      => 'Tilbage til webkamera',
    'full_size'           => 'Fuld størrelse',
    'prev_image'          => 'Forrige',
    'next_image'          => 'Næste',
    'more_photos_header'  => 'Lillevik Lofoten: Flere billeder',
    'more_photos_intro'   => 'Billederne nedenfor er taget ved <a href="https://lilleviklofoten.no?utm_source=webcam">Lillevik Lofoten</a> eller i nærheden på Gimsøy.',
    'more_photos_booking' => 'Information og booking: <a href="https://lilleviklofoten.no?utm_source=webcam">lilleviklofoten.no</a>.',
    'more_photos_reload'  => 'Nye billeder: <a href="#" onclick="location.reload(); return false;">Genindlæs</a>.',
    'made_with'           => 'Lavet med',
    'aurora_page_suffix'  => 'Nordlys',
    'aurora_forecast'     => 'Nordlysprognose for Lofoten',
    'aurora_tonight'      => 'I aften',
    'aurora_tomorrow'     => 'I morgen nat',
    'aurora_no_activity'  => 'Ingen aktivitet',
    'aurora_low'          => 'Lav',
    'aurora_medium'       => 'Middel',
    'aurora_high'         => 'Høj',
    'aurora_extreme'      => 'Ekstrem',
    'cloud_clear'         => 'Klart',
    'cloud_few'           => 'Let skyet',
    'cloud_partly'        => 'Delvis skyet',
    'cloud_cloudy'        => 'Skyet',
    'cloud_overcast'      => 'Overskyet',
    'cloud_fog'           => 'Tåge',
    'aurora_updated'      => 'opdateret',
    'aurora_no_photos'    => 'Ingen nordlysbilleder for %s',
    'aurora_credit'       => 'Nordlysdetektering af <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">aurora_scan.py</a>. Billedtekst: dag, tid og score.',
    'aurora_intro'        => '<a href=".">Webkamera</a> ved <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norge.',
    'aurora_see_also'     => 'Se også: <a href="https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/">Nordlys ved Lillevik Lofoten</a>.',
    'months'             => ['januar', 'februar', 'marts', 'april', 'maj', 'juni', 'juli', 'august', 'september', 'oktober', 'november', 'december'],
    'webcam_intro'        => '<a href=".">Webkamera</a> ved <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norge. Se også: <a href="https://lilleviklofoten.no/webcams/">Lofoten-webkameraer ved Gimsøy, Henningsvær, Reine, Svolvær, Leknes m.fl.</a>',
    'people_no_photos'    => 'Ingen personbilleder for %s',
    'people_credit'       => 'Persondetektering af <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">people_scan.py</a> med YOLOv8. Etiket: dag, tid og konfidensscorer.',
],

// ============================================================
'pl' => [
    'nav_swipe_or_use'    => 'Przesuń lub użyj',
    'nav_use'             => 'Użyj',
    'nav_arrow_keys'      => 'klawiszy strzałek do nawigacji:',
    'nav_forward'         => 'dalej',
    'nav_back'            => 'wstecz',
    'nav_up'              => 'w górę',
    'nav_down'            => 'w dół',
    'nav_and'             => 'i',
    'nav_today'           => 'Dziś',
    'nav_latest'          => 'Najnowszy obraz',
    'nav_mini_photos'     => 'Małe zdjęcia',
    'nav_large_photos'    => 'Duże zdjęcia',
    'nav_now'             => 'Teraz',
    'nav_entire'          => 'Cały',
    'nav_whole_day'       => 'Cały dzień',
    'nav_months'          => 'Miesiące',
    'nav_and_conj'        => 'i',
    'nav_webcam'          => 'Kamera',
    'nav_aurora'          => 'Zorza polarna',
    'nav_people'          => 'Osoby',
    'midnight_sun'        => 'Słońce o północy',
    'polar_night'         => 'Noc polarna',
    'sunrise'             => 'Wschód słońca',
    'sunset'              => 'Zachód słońca',
    'displaying_between'  => 'Zdjęcia między %s a %s',
    'calculated_for'      => 'obliczono dla %s %d',
    'weather'             => 'Pogoda',
    'source'              => 'Źródło',
    'feels_like'          => 'odczuwalne',
    'gusts'               => 'porywy',
    'max_wind'            => 'maks. wiatr',
    'no_photos'           => 'Brak zdjęć dla %s',
    'no_image_found'      => 'Nie znaleziono obrazu.',
    'back_to_webcam'      => 'Powrót do kamery',
    'full_size'           => 'Pełny rozmiar',
    'prev_image'          => 'Poprzedni',
    'next_image'          => 'Następny',
    'more_photos_header'  => 'Lillevik Lofoten: Więcej zdjęć',
    'more_photos_intro'   => 'Poniższe zdjęcia zostały wykonane w <a href="https://lilleviklofoten.no?utm_source=webcam">Lillevik Lofoten</a> lub w pobliżu na Gimsøy.',
    'more_photos_booking' => 'Informacje i rezerwacje: <a href="https://lilleviklofoten.no?utm_source=webcam">lilleviklofoten.no</a>.',
    'more_photos_reload'  => 'Nowe zdjęcia: <a href="#" onclick="location.reload(); return false;">Odśwież</a>.',
    'made_with'           => 'Stworzone za pomocą',
    'aurora_page_suffix'  => 'Zorza polarna',
    'aurora_forecast'     => 'Prognoza zorzy polarnej dla Lofoten',
    'aurora_tonight'      => 'Dziś w nocy',
    'aurora_tomorrow'     => 'Jutro w nocy',
    'aurora_no_activity'  => 'Brak aktywności',
    'aurora_low'          => 'Niska',
    'aurora_medium'       => 'Średnia',
    'aurora_high'         => 'Wysoka',
    'aurora_extreme'      => 'Ekstremalna',
    'cloud_clear'         => 'Bezchmurnie',
    'cloud_few'           => 'Lekkie zachmurzenie',
    'cloud_partly'        => 'Częściowe zachmurzenie',
    'cloud_cloudy'        => 'Zachmurzenie',
    'cloud_overcast'      => 'Pełne zachmurzenie',
    'cloud_fog'           => 'Mgła',
    'aurora_updated'      => 'zaktualizowano',
    'aurora_no_photos'    => 'Brak zdjęć zorzy dla %s',
    'aurora_credit'       => 'Wykrywanie zorzy przez <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">aurora_scan.py</a>. Etykieta: dzień, godzina i wynik.',
    'aurora_intro'        => '<a href=".">Kamera</a> w <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norwegia.',
    'aurora_see_also'     => 'Zobacz też: <a href="https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/">Zorza polarna w Lillevik Lofoten</a>.',
    'months'             => ['styczeń', 'luty', 'marzec', 'kwiecień', 'maj', 'czerwiec', 'lipiec', 'sierpień', 'wrzesień', 'październik', 'listopad', 'grudzień'],
    'webcam_intro'        => '<a href=".">Kamera</a> w <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norwegia. Zobacz też: <a href="https://lilleviklofoten.no/webcams/">Kamery Lofoten w Gimsøy, Henningsvær, Reine, Svolvær, Leknes i in.</a>',
    'people_no_photos'    => 'Brak zdjęć z osobami dla %s',
    'people_credit'       => 'Wykrywanie osób przez <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">people_scan.py</a> z YOLOv8. Etykieta: dzień, godzina i pewność.',
],

// ============================================================
'fi' => [
    'nav_swipe_or_use'    => 'Pyyhkäise tai käytä',
    'nav_use'             => 'Käytä',
    'nav_arrow_keys'      => 'nuolinäppäimiä navigointiin:',
    'nav_forward'         => 'eteenpäin',
    'nav_back'            => 'takaisin',
    'nav_up'              => 'ylös',
    'nav_down'            => 'alas',
    'nav_and'             => 'ja',
    'nav_today'           => 'Tänään',
    'nav_latest'          => 'Viimeisin kuva',
    'nav_mini_photos'     => 'Pienet kuvat',
    'nav_large_photos'    => 'Suuret kuvat',
    'nav_now'             => 'Nyt',
    'nav_entire'          => 'Kaikki',
    'nav_whole_day'       => 'Koko päivä',
    'nav_months'          => 'Kuukaudet',
    'nav_and_conj'        => 'ja',
    'nav_webcam'          => 'Verkkokamera',
    'nav_aurora'          => 'Revontulet',
    'nav_people'          => 'Henkilöt',
    'midnight_sun'        => 'Keskiyön aurinko',
    'polar_night'         => 'Kaamos',
    'sunrise'             => 'Auringonnousu',
    'sunset'              => 'Auringonlasku',
    'displaying_between'  => 'Kuvat %s–%s',
    'calculated_for'      => 'laskettu %s %d.',
    'weather'             => 'Sää',
    'source'              => 'Lähde',
    'feels_like'          => 'tuntuu kuin',
    'gusts'               => 'puuskat',
    'max_wind'            => 'maks. tuuli',
    'no_photos'           => 'Ei kuvia %s',
    'no_image_found'      => 'Kuvaa ei löydy.',
    'back_to_webcam'      => 'Takaisin verkkokameraan',
    'full_size'           => 'Täysi koko',
    'prev_image'          => 'Edellinen',
    'next_image'          => 'Seuraava',
    'more_photos_header'  => 'Lillevik Lofoten: Lisää kuvia',
    'more_photos_intro'   => 'Alla olevat kuvat on otettu <a href="https://lilleviklofoten.no?utm_source=webcam">Lillevik Lofoten</a>issa tai lähialueella Gimsøyssä.',
    'more_photos_booking' => 'Tietoa ja varaukset: <a href="https://lilleviklofoten.no?utm_source=webcam">lilleviklofoten.no</a>.',
    'more_photos_reload'  => 'Uusia kuvia: <a href="#" onclick="location.reload(); return false;">Lataa uudelleen</a>.',
    'made_with'           => 'Tehty käyttäen',
    'aurora_page_suffix'  => 'Revontulet',
    'aurora_forecast'     => 'Revontuliennuste Lofooteille',
    'aurora_tonight'      => 'Tänä yönä',
    'aurora_tomorrow'     => 'Huomenna yöllä',
    'aurora_no_activity'  => 'Ei aktiivisuutta',
    'aurora_low'          => 'Matala',
    'aurora_medium'       => 'Kohtalainen',
    'aurora_high'         => 'Korkea',
    'aurora_extreme'      => 'Äärimmäinen',
    'cloud_clear'         => 'Selkeää',
    'cloud_few'           => 'Vähän pilviä',
    'cloud_partly'        => 'Puolipilvistä',
    'cloud_cloudy'        => 'Pilvistä',
    'cloud_overcast'      => 'Täysin pilvistä',
    'cloud_fog'           => 'Sumua',
    'aurora_updated'      => 'päivitetty',
    'aurora_no_photos'    => 'Ei revontulivalokuvia %s',
    'aurora_credit'       => 'Revontulihavainto <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">aurora_scan.py</a>:lla. Kuvan teksti: päivä, aika ja pistemäärä.',
    'aurora_intro'        => '<a href=".">Verkkokamera</a> kohteessa <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norja.',
    'aurora_see_also'     => 'Katso myös: <a href="https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/">Revontulet Lillevik Lofotenissa</a>.',
    'months'             => ['tammikuu', 'helmikuu', 'maaliskuu', 'huhtikuu', 'toukokuu', 'kesäkuu', 'heinäkuu', 'elokuu', 'syyskuu', 'lokakuu', 'marraskuu', 'joulukuu'],
    'webcam_intro'        => '<a href=".">Verkkokamera</a> kohteessa <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Norja. Katso myös: <a href="https://lilleviklofoten.no/webcams/">Lofoottien verkkokamerat Gimsøyssä, Henningsvärissä, Reinessä, Svolværissä, Leknesissa jne.</a>',
    'people_no_photos'    => 'Ei henkilövalokuvia %s',
    'people_credit'       => 'Henkilöhavainto <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">people_scan.py</a>:lla YOLOv8:n avulla. Teksti: päivä, aika ja luotettavuus.',
],

// ============================================================
'pt' => [
    'nav_swipe_or_use'    => 'Deslize ou use',
    'nav_use'             => 'Use',
    'nav_arrow_keys'      => 'as teclas de seta para navegar:',
    'nav_forward'         => 'avançar',
    'nav_back'            => 'voltar',
    'nav_up'              => 'cima',
    'nav_down'            => 'baixo',
    'nav_and'             => 'e',
    'nav_today'           => 'Hoje',
    'nav_latest'          => 'Imagem mais recente',
    'nav_mini_photos'     => 'Fotos pequenas',
    'nav_large_photos'    => 'Fotos grandes',
    'nav_now'             => 'Agora',
    'nav_entire'          => 'Todo',
    'nav_whole_day'       => 'Dia inteiro',
    'nav_months'          => 'Meses',
    'nav_and_conj'        => 'e',
    'nav_webcam'          => 'Webcam',
    'nav_aurora'          => 'Aurora boreal',
    'nav_people'          => 'Pessoas',
    'midnight_sun'        => 'Sol da meia-noite',
    'polar_night'         => 'Noite polar',
    'sunrise'             => 'Nascer do sol',
    'sunset'              => 'Pôr do sol',
    'displaying_between'  => 'Fotos entre %s e %s',
    'calculated_for'      => 'calculado para %s %d',
    'weather'             => 'Tempo',
    'source'              => 'Fonte',
    'feels_like'          => 'sensação',
    'gusts'               => 'rajadas',
    'max_wind'            => 'vento máx.',
    'no_photos'           => 'Sem fotos para %s',
    'no_image_found'      => 'Imagem não encontrada.',
    'back_to_webcam'      => 'Voltar à webcam',
    'full_size'           => 'Tamanho original',
    'prev_image'          => 'Anterior',
    'next_image'          => 'Próxima',
    'more_photos_header'  => 'Lillevik Lofoten: Mais fotos',
    'more_photos_intro'   => 'As fotos abaixo foram tiradas em <a href="https://lilleviklofoten.no?utm_source=webcam">Lillevik Lofoten</a>, ou perto em Gimsøy.',
    'more_photos_booking' => 'Informações e reservas: <a href="https://lilleviklofoten.no?utm_source=webcam">lilleviklofoten.no</a>.',
    'more_photos_reload'  => 'Novas fotos: <a href="#" onclick="location.reload(); return false;">Recarregar</a>.',
    'made_with'           => 'Criado com',
    'aurora_page_suffix'  => 'Aurora boreal',
    'aurora_forecast'     => 'Previsão de auroras para Lofoten',
    'aurora_tonight'      => 'Esta noite',
    'aurora_tomorrow'     => 'Amanhã à noite',
    'aurora_no_activity'  => 'Sem atividade',
    'aurora_low'          => 'Fraca',
    'aurora_medium'       => 'Média',
    'aurora_high'         => 'Alta',
    'aurora_extreme'      => 'Extrema',
    'cloud_clear'         => 'Limpo',
    'cloud_few'           => 'Poucas nuvens',
    'cloud_partly'        => 'Parcialmente nublado',
    'cloud_cloudy'        => 'Nublado',
    'cloud_overcast'      => 'Encoberto',
    'cloud_fog'           => 'Nevoeiro',
    'aurora_updated'      => 'atualizado',
    'aurora_no_photos'    => 'Sem fotos de aurora para %s',
    'aurora_credit'       => 'Deteção de aurora por <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">aurora_scan.py</a>. Sobreposição: dia, hora e pontuação.',
    'aurora_intro'        => '<a href=".">Webcam</a> em <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Noruega.',
    'aurora_see_also'     => 'Veja também: <a href="https://lilleviklofoten.no/en/northern-lights-at-lillevik-lofoten/">Aurora boreal em Lillevik Lofoten</a>.',
    'months'             => ['janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro'],
    'webcam_intro'        => '<a href=".">Webcam</a> em <a href="https://lilleviklofoten.no">Lillevik Lofoten</a>, Vik, Gimsøy, Lofoten, Noruega. Veja também: <a href="https://lilleviklofoten.no/webcams/">Webcams de Lofoten em Gimsøy, Henningsvær, Reine, Svolvær, Leknes, etc.</a>',
    'people_no_photos'    => 'Sem fotos com pessoas para %s',
    'people_credit'       => 'Deteção de pessoas por <a style="color: rgb(200, 200, 200);" href="https://github.com/cloveras/webcam">people_scan.py</a> com YOLOv8. Etiqueta: dia, hora e confiança.',
],

]; // end $TRANSLATIONS
